name: Build and Deploy Node.js App to Azure Web App - docease-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build

      - name: Prepare deploy folder
        run: |
          mkdir deploy
          cp -r .next public package.json node_modules deploy/

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_08BE1E9E529C472BAA21C27BA45AB512 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_22C566F1E58D4C5FBFBD944E959FAA88 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1C9FEA3533BA40EAB5FABDF472C6CA58 }}


      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'docease-app'
          slot-name: 'Production'
          package: .next/
